from app.blueprints.admin.views import admin  # noqa
from app.blueprints.admin import errors  # noqa
from app.blueprints.admin.social import social  # noqa
from app.blueprints.admin.tracking import tracking  # noqa
from app.blueprints.admin.testimonial import testimonial  # noqa
from app.blueprints.admin.services import services  # noqa
from app.blueprints.admin.call2action import call2action  # noqa
from app.blueprints.admin.team import team  # noqa
from app.blueprints.admin.html import html  # noqa
from app.blueprints.admin.about import about  # noqa
from app.blueprints.admin.brands import brands  # noqa
from app.blueprints.admin.portfolio import portfolio  # noqa
from app.blueprints.admin.newslink import newslink  # noqa
from app.blueprints.admin.organisation import organisation  # noqa
from app.blueprints.admin.upload import image_upload  # noqa
from app.blueprints.admin.orgstaff import orgstaff  # noqa
from app.blueprints.admin.preview import preview  # noqa
from app.blueprints.admin.contact import contact  # noqa
from app.blueprints.admin.teamsection import teamsection  # noqa
from app.blueprints.admin.testimonialsection import testimonialsection  # noqa
