from app.blueprints.admin.views import admin  # noqa
from app.blueprints.admin import errors  # noqa
from app.blueprints.admin.social import social  # noqa
from app.blueprints.admin.tracking import tracking  # noqa
from app.blueprints.admin.testimonial import testimonial  # noqa
from app.blueprints.admin.services import services  # noqa
from app.blueprints.admin.call2action import call2action  # noqa
from app.blueprints.admin.team import team  # noqa
from app.blueprints.admin.html import html  # noqa
from app.blueprints.admin.about import about  # noqa