"""empty message

Revision ID: 068176fb58dd
Revises: 1405fd5908fc
Create Date: 2020-09-13 22:07:11.215318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068176fb58dd'
down_revision = '1405fd5908fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call2actions', sa.Column('action_button_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call2actions', 'action_button_text')
    # ### end Alembic commands ###
