"""empty message

Revision ID: 0b9567b5d7a1
Revises: 3811085c03c3
Create Date: 2020-09-14 14:00:16.753083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9567b5d7a1'
down_revision = '3811085c03c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamsections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('section_description', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('teammembers', 'section_name')
    op.drop_column('teammembers', 'section_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammembers', sa.Column('section_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teammembers', sa.Column('section_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('teamsections')
    # ### end Alembic commands ###
