"""empty message

Revision ID: 1405fd5908fc
Revises: f8482a418645
Create Date: 2020-09-13 22:06:03.420709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1405fd5908fc'
down_revision = 'f8482a418645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call2actions', sa.Column('action_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call2actions', 'action_title')
    # ### end Alembic commands ###
