"""empty message

Revision ID: 2d433092f940
Revises: 1b06ae54de4e
Create Date: 2020-09-14 21:51:30.029335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d433092f940'
down_revision = '1b06ae54de4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_intro', sa.String(), nullable=True))
    op.drop_column('services', 'services_intro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('services_intro', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('services', 'service_intro')
    # ### end Alembic commands ###
