"""empty message

Revision ID: 3811085c03c3
Revises: 068176fb58dd
Create Date: 2020-09-14 13:43:31.857807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3811085c03c3'
down_revision = '068176fb58dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammembers', sa.Column('section_description', sa.String(), nullable=True))
    op.add_column('teammembers', sa.Column('section_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teammembers', 'section_name')
    op.drop_column('teammembers', 'section_description')
    # ### end Alembic commands ###
