"""empty message

Revision ID: 3aa25638dd19
Revises: a4b67beeb8d1
Create Date: 2020-09-13 20:33:33.044351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa25638dd19'
down_revision = 'a4b67beeb8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'image')
    # ### end Alembic commands ###
