"""empty message

Revision ID: a04bc616bd1e
Revises: 2da0c70186db
Create Date: 2020-09-08 08:38:13.962679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04bc616bd1e'
down_revision = '2da0c70186db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('image', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('organisation_id', sa.Integer(), nullable=False))
    op.add_column('photos', sa.Column('owner_organisation', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'photos', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('photos', 'image_filename')
    op.drop_column('photos', 'image_url')
    op.add_column('teammembers', sa.Column('team_member_picture', sa.String(), nullable=True))
    op.drop_column('teammembers', 'team_member_person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammembers', sa.Column('team_member_person', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teammembers', 'team_member_picture')
    op.add_column('photos', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'owner_organisation')
    op.drop_column('photos', 'organisation_id')
    op.drop_column('photos', 'image')
    # ### end Alembic commands ###
