"""empty message

Revision ID: bbc1de274600
Revises: 0a7626501af1
Create Date: 2020-09-11 18:47:07.026673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc1de274600'
down_revision = '0a7626501af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'image_filename')
    op.drop_column('organisations', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organisations', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
