"""empty message

Revision ID: beeb7b850ddc
Revises: 
Create Date: 2020-09-06 13:59:36.474991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beeb7b850ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('org_city', sa.String(length=255), nullable=True),
    sa.Column('org_state', sa.String(length=255), nullable=True),
    sa.Column('org_country', sa.String(length=255), nullable=True),
    sa.Column('org_website', sa.String(length=255), nullable=True),
    sa.Column('org_short_description', sa.String(length=255), nullable=True),
    sa.Column('org_industry', sa.String(length=255), nullable=True),
    sa.Column('org_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_us_title', sa.String(), nullable=True),
    sa.Column('key_information_title_one', sa.String(), nullable=True),
    sa.Column('key_information_title_two', sa.String(), nullable=True),
    sa.Column('key_information_title_three', sa.String(), nullable=True),
    sa.Column('key_information_description_one', sa.String(), nullable=True),
    sa.Column('key_information_description_two', sa.String(), nullable=True),
    sa.Column('key_information_description_three', sa.String(), nullable=True),
    sa.Column('key_information_icon_one', sa.String(), nullable=True),
    sa.Column('key_information_icon_two', sa.String(), nullable=True),
    sa.Column('key_information_icon_three', sa.String(), nullable=True),
    sa.Column('key_information_numbers_one', sa.String(), nullable=True),
    sa.Column('key_information_numbers_two', sa.String(), nullable=True),
    sa.Column('key_information_numbers_three', sa.String(), nullable=True),
    sa.Column('key_information_numbers_four', sa.String(), nullable=True),
    sa.Column('key_information_numbers_description_one', sa.String(), nullable=True),
    sa.Column('key_information_numbers_description_two', sa.String(), nullable=True),
    sa.Column('key_information_numbers_description_three', sa.String(), nullable=True),
    sa.Column('key_information_numbers_description_four', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call2actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('call2action_url', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('spam', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_name', sa.String(), nullable=True),
    sa.Column('portfolio_title', sa.String(), nullable=True),
    sa.Column('portfolio_description', sa.String(), nullable=True),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('services_intro', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('service_description', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teammembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('team_member_facebook', sa.String(), nullable=True),
    sa.Column('team_member_twitter', sa.String(), nullable=True),
    sa.Column('team_member_person', sa.String(), nullable=True),
    sa.Column('team_member_linkedin', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('owner_organisation', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teammembers')
    op.drop_table('services')
    op.drop_table('portfolios')
    op.drop_table('logos')
    op.drop_table('contact_messages')
    op.drop_table('call2actions')
    op.drop_table('abouts')
    op.drop_table('organisations')
    op.drop_table('photos')
    # ### end Alembic commands ###
