"""empty message

Revision ID: c5ab278334e4
Revises: bbc1de274600
Create Date: 2020-09-13 09:10:35.955814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ab278334e4'
down_revision = 'bbc1de274600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammembers', sa.Column('image', sa.String(), nullable=True))
    op.add_column('teammembers', sa.Column('team_member_instagram', sa.String(), nullable=True))
    op.drop_column('teammembers', 'team_member_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teammembers', sa.Column('team_member_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teammembers', 'team_member_instagram')
    op.drop_column('teammembers', 'image')
    # ### end Alembic commands ###
