"""empty message

Revision ID: c60b807c925f
Revises: de7b69ac9b2f
Create Date: 2020-09-11 17:29:30.653237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60b807c925f'
down_revision = 'de7b69ac9b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'file_name')
    # ### end Alembic commands ###
