"""empty message

Revision ID: c9c2bcfee4a7
Revises: d6f6dc0b5e20
Create Date: 2020-09-14 17:16:10.707508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c2bcfee4a7'
down_revision = 'd6f6dc0b5e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('portfolio_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'portfolio_price')
    op.drop_column('portfolios', 'currency')
    # ### end Alembic commands ###
