"""empty message

Revision ID: d6f6dc0b5e20
Revises: 43f225bc7aec
Create Date: 2020-09-14 15:49:26.794470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f6dc0b5e20'
down_revision = '43f225bc7aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('portfolio_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'portfolio_category')
    # ### end Alembic commands ###
