"""empty message

Revision ID: de7b69ac9b2f
Revises: 
Create Date: 2020-09-11 16:50:58.000475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7b69ac9b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logos', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('logos', 'image_url')
    op.drop_column('logos', 'image_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logos', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logos', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('logos', 'image')
    # ### end Alembic commands ###
