"""empty message

Revision ID: e8a00abe41c1
Revises: a04bc616bd1e
Create Date: 2020-09-10 09:27:55.897608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a00abe41c1'
down_revision = 'a04bc616bd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('portfolios', 'image_url')
    op.drop_column('portfolios', 'image_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('portfolios', 'image')
    # ### end Alembic commands ###
