"""empty message

Revision ID: f8482a418645
Revises: 3aa25638dd19
Create Date: 2020-09-13 21:23:57.464285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8482a418645'
down_revision = '3aa25638dd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('job_title', sa.String(), nullable=True))
    op.drop_column('testimonials', 'testimonial_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonials', sa.Column('testimonial_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('testimonials', 'job_title')
    # ### end Alembic commands ###
